import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import CitiesList from "../components/CitiesList";
import CitiesMap from "../components/CitiesMap";
import { useAppSelector } from "../redux/store";

const Home: NextPage = () => {
  const { isActive } = useAppSelector((store) => store.option);
  return (
    <div className="p-8 bg-[#0d2546]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-6xl mx-auto">
      <h2 className="text-4xl text-center text-white font-semibold">İllere Göre Hava Durumu</h2>
        <Header />
        {isActive === "Liste" ? <CitiesList /> : <CitiesMap />}
      </div>
    </div>
  );
};

export default Home;
